### ISSUE TITLE
Create a new Welcome page separate from the Introduction page

### ISSUE THREAD

**Issue by daviswx** [ncsco/voyager-help#3]
Per Aaron's suggestion, add a Welcome page only including the text and image from the current Background tab.  That way, people looking for the tools won't see the "Climate Data" tab and think that's how they access them.

The current Introduction page (minus the Background tab) could still be reached through the top menu or linked on this Welcome page.

(@hadinon, feel free to expand on this if I missed anything.)

**Comment by daviswx** [comment]
I've got a new Welcome page in place on the Climate Voyager dev site.  Please pass along any comments or suggestions.

**Comment by daviswx** [comment]
Suggestion: Hide the middle 4 paragraphs inside a "Read more..." link.

**Comment by hadinon** [comment]
Re-word "Because a wide range..." sentence as "Because a wide range of climate outcomes is possible, these tools show more than one solution." and replace "Instead," in the next sentence to, "To do this,".
