### ISSUE TITLE
Add link under "Other Resources" on Plant Hardiness Zone tool

### ISSUE THREAD

**Issue by hadinon** [ncsco/voyager-help#7]
Under "Other Resources" of the Plant Hardiness Zone tool, add a link to the data source of the ramps locations, BISON: https://bison.usgs.gov/#home

**Comment by hadinon** [comment]
Update: Alexa says she thinks BISON requests that the data providers and BISON be acknowledged. She emailed us a list of data providers and links. I have two ideas for how to implement this:
- Under "Other Resources", add a sentence saying, "For more information on..." and at the end of this statement, add a tooltip that acknowledges BISON as a whole and perhaps links to an FAQ with the list of data providers.
- Beside "Ramps locations" within the Layer Options menu, include a tooltip that acknowledges BISON as a whole and perhaps links to an FAQ with the list of data providers.

Do you have any other ideas?

**Comment by daviswx** [comment]
I have a few thoughts:
- Putting the credit under "Other Resources" might be (a) redundant since it would appear on every tool, and (b) easy to miss since the attribution wouldn't appear near anything related to the layer itself.
- Putting it next to the "Ramps locations" text in the Layer Options menu seems like a good idea.  Maybe we could change it to say "Ramps locations (from BISON)" and link the "BISON" text to that USGS link.
- In addition to (or instead of) that, we could add an attribution on the FAQ section about map layers (under the Navigation tab).

**Comment by hadinon** [comment]
I like bullets 2 and 3. It sounds like Alexa wants us to reference BISON as a whole AND these 13 sources, which have fed their data into BISON's database:
![image](https://cloud.githubusercontent.com/assets/886682/18992558/f69d4b1a-86ec-11e6-8451-5bbb8a6397a0.png)
(BISON reminds me of CRONOS -- you can download a temperature dataset that contains different station types that have been ingested from various data providers/sources.)

Perhaps we could list the source names (within the "InstitutionCode" column) in the FAQ about map layers, linking the source name text to the associated source link, e.g., "The historical ramps locations have been downloaded from the Biodiversity Information Serving Our Nation ([BISON](https://bison.usgs.gov/)) database, which compiles ramps data from several sources including [Field Museum](http://emuweb.fieldmuseum.org/botany/Query.php), [Michigan State University Herbarium](http://herbarium.msu.edu), ...." Thoughts?

**Comment by daviswx** [comment]
Just to clarify your idea, would you list all 13 sources in that sentence?  Like would you say "The historical ramps locations have been downloaded from the Biodiversity Information Serving Our Nation (BISON) database, which compiles ramps data from several sources including Field Museum, Michigan State University Herbarium, Missouri Botanical Garden, [and so on for the next 9], and the University of British Columbia."

**Comment by daviswx** [comment]
The tooltip and FAQ for the Ramps Locations layer are now in place.

**Comment by hadinon** [comment]
Aranzazu and Alexa approved.
